name: Trigger Geobackend Update

on:
  release:
    types: [published]

jobs:
  trigger-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Update Dependencies Workflow in Geobackend
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token $REPO_TOKEN" \
        --data '{"event_type": "update_dependencies"}' \
        https://api.github.com/repos/08dhuh/geobackend/dispatches
